#!/bin/bash

# Starting registry
docker run -d -p 5000:5000 --name arun_registry registry:2

# Tag the image to point it to your registry
docker tag arun:tomcat localhost:5000/tomcat

# Push to image to the registry
docker push localhost:5000/tomcat

# Pull the registry back
docker pull localhost:5000/tomcat

# Stop your registry and remove all data
#docker stop arun_registry && docker rm -v arun_registry
